import assert from "node:assert/strict";import {readFile} from "node:fs/promises";import {describe,it} from "node:test";import {parseActivityResponse,parseExecutionResponse,parseReceiptResponse} from "../src/lib/paymentIntents/executionContract";import {parseCreateInput} from "../src/lib/paymentIntents/requests";
const paymentIntentId="00000000-0000-4000-8000-000000000001",executionId="00000000-0000-4000-8000-000000000002",now="2026-08-07T12:00:00.000Z",rail={id:"mock",label:"Mock Rail"},recipient={type:"payment_identity",displayName:"Recipient",username:"recipient",verificationState:"verified",trustOutcome:"not_required"};
const execution=(status:string)=>({ok:true,execution:{executionId,paymentIntentId,status,rail,createdAt:now,receiptAvailable:status==="settled",retryAllowed:false,stillProcessing:["processing","pending"].includes(status),reconciliationPending:status==="pending"}});
describe("Phase C frontend contracts",()=>{
 it("accepts every public execution state without internal authority fields",()=>{for(const status of ["ready","processing","pending","settled","failed","cancelled"])assert.equal(parseExecutionResponse(execution(status))?.status,status);assert.equal(parseExecutionResponse({...execution("processing"),execution:{...execution("processing").execution,status:"UNKNOWN"}}),undefined)});
 it("accepts authoritative settled receipts and canonical null memo",()=>{const value={ok:true,receipt:{receiptId:"receipt:test",paymentIntentId,executionId,status:"settled",amountRaw:"2000000",amount:"2",asset:"USDC",sender:{displayName:"You"},recipient,memo:null,rail,settledAt:now,verification:{receiptSchemaVersion:1,evidenceType:"mock.execution",evidenceVersion:1,requestHash:"a".repeat(64)}}};assert.equal(parseReceiptResponse(value)?.memo,null);assert.equal(parseReceiptResponse({...value,receipt:{...value.receipt,status:"processing"}}),undefined)});
 it("preserves backend activity order, immutable snapshot, and optional memo",()=>{const first={paymentIntentId,executionId,receiptId:"receipt:test",status:"completed",recipient,amountRaw:"2000000",amount:"2",asset:"USDC",memo:null,createdAt:now,settledAt:now,receiptAvailable:true},second={...first,paymentIntentId:"00000000-0000-4000-8000-000000000003",status:"pending",memo:"Dinner",receiptAvailable:false};const parsed=parseActivityResponse({ok:true,items:[first,second]});assert.deepEqual(parsed?.map(i=>i.paymentIntentId),[first.paymentIntentId,second.paymentIntentId]);assert.equal(parsed?.[0].memo,null);assert.equal(parsed?.[1].recipient.displayName,"Recipient")});
 it("normalizes empty purpose without blocking valid payment construction",()=>{const base={recipient:"11111111111111111111111111111111",amount:"2"};for(const purpose of [undefined,null,"","   "])assert.equal(parseCreateInput({...base,...(purpose===undefined?{}:{purpose})})?.purpose,null);assert.equal(parseCreateInput({...base,purpose:" Dinner "})?.purpose,"Dinner")});
 it("wires bounded polling, receipt recovery, activity refresh, and omits blank purpose rows",async()=>{const workspace=await source("src/components/product/personal/PaymentIntentWorkspace.tsx"),activity=await source("src/components/product/personal/ActivityInterfacePreview.tsx");assert.match(workspace,/setTimeout\(poll,2500\)/);assert.match(workspace,/setTimeout\(poll,4000\)/);assert.match(workspace,/c\.abort\(\)/);assert.match(workspace,/if\(polling\.current\)return/);assert.match(workspace,/parsed\.status==="settled"/);assert.match(workspace,/receipt\.memo\?/);assert.match(workspace,/zephipay:activity-refresh/);assert.match(activity,/\/api\/activity\?limit=20/);assert.match(activity,/selected\.memo\?/);assert.doesNotMatch(workspace,/\/api\/send|providerIdempotencyKey|selectedRail/);assert.doesNotMatch(activity,/push\(|unshift\(|localStorage|sessionStorage/)})
});async function source(path:string){return readFile(new URL(`../${path}`,import.meta.url),"utf8")}
