import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { describe, it } from "node:test";

describe("open-beta final site audit", () => {
  it("removes the internal design page from public discovery and redirects direct visits", async () => {
    const navigation = await source("src/config/navigation.ts");
    const footer = await source("src/components/layout/SiteFooter.tsx");
    const design = await source("src/app/design/page.tsx");
    assert.doesNotMatch(`${navigation}\n${footer}`, /Design system|href:\s*["']\/design["']/);
    assert.match(design, /import \{ redirect \} from "next\/navigation"/);
    assert.match(design, /redirect\("\/"\)/);
    assert.doesNotMatch(design, /Color system|Components|Typography|colorSwatches/);
  });

  it("rejects synthetic beta Request without weakening synthetic Send", async () => {
    const compose = await source("src/components/product/personal/PaymentComposeForm.tsx");
    assert.match(compose, /flow === "request" && recipient\.identitySource === "synthetic_beta"/);
    assert.match(compose, /cannot sign in to accept requests/);
    assert.match(compose, /const mode = trustModeForRecipient\(recipient\)/);
    assert.doesNotMatch(compose, /flow === "send" && recipient\.identitySource === "synthetic_beta"/);
  });

  it("uses consumer payment terminology without changing authoritative status values", async () => {
    const activity = await source("src/components/product/personal/ActivityInterfacePreview.tsx");
    assert.match(activity, /v==="completed"\?"Payment sent"/);
    assert.match(activity, /v==="pending"\?"Confirming payment"/);
    assert.match(activity, /v==="ready"\|\|v==="processing"\?"Sending payment"/);
    assert.doesNotMatch(activity, /v==="completed"\?"Settled"|v==="ready"\?"Queued"|v==="pending"\?"Status still being confirmed"/);
  });

  it("ships ZephiPay metadata instead of framework starter metadata", async () => {
    const layout = await source("src/app/layout.tsx");
    assert.match(layout, /title: "ZephiPay \| Modern payments without the complexity"/);
    assert.match(layout, /description: "ZephiPay coordinates clear, trusted payment experiences/);
    assert.doesNotMatch(layout, /Create Next App|Generated by create next app/);
  });
});

async function source(path: string) {
  return readFile(new URL(`../${path}`, import.meta.url), "utf8");
}
