import assert from "node:assert/strict";import{readFile}from"node:fs/promises";import{describe,it}from"node:test";import{parsePaymentRequestCreateResponse,parsePaymentRequestListResponse}from"../src/lib/paymentRequests/contract";import{parseCreatePaymentRequest,parseRequestCommand}from"../src/lib/paymentRequests/requests";
const ID="00000000-0000-4000-8000-000000000001",OTHER="00000000-0000-4000-8000-000000000002",at="2026-08-08T12:00:00.000Z";const party=(accountId:string)=>({accountId,username:"nova",displayName:"Nova",accountType:"personal",verificationState:"verified",capturedAt:at,schemaVersion:1});const request={requestId:ID,role:"requester",direction:"requested",status:"pending",version:"0",requestHash:"a".repeat(64),requester:party(ID),payer:party(OTHER),amountRaw:"2000000",amount:"2",asset:"USDC",purpose:null,createdAt:at,updatedAt:at};
describe("Personal Send, Request, and Transfer interface",()=>{
 it("strictly validates request creation, optional purpose, positive exact amounts, and commands",()=>{assert.deepEqual(parseCreatePaymentRequest({payerAccountId:OTHER,amount:"2",purpose:"  "}),{payerAccountId:OTHER,amount:"2",purpose:null});assert.equal(parseCreatePaymentRequest({payerAccountId:OTHER,amount:"0",purpose:null}),undefined);assert.equal(parseCreatePaymentRequest({payerAccountId:OTHER,amount:"2",purpose:null,status:"paid"}),undefined);assert.deepEqual(parseRequestCommand({expectedVersion:"0"}),{expectedVersion:"0"});assert.equal(parseRequestCommand({expectedVersion:"0",trustAcknowledgment:{acknowledged:true}}),undefined)});
 it("parses authoritative pending and paid request activity without fabricating receipts",()=>{assert.equal(parsePaymentRequestCreateResponse({ok:true,paymentRequest:request,created:true})?.paymentRequest.status,"pending");assert.equal(parsePaymentRequestListResponse({ok:true,items:[{...request,status:"paid",paidAt:at,linkedReceiptId:OTHER}]})?.items[0].status,"paid");assert.equal(parsePaymentRequestListResponse({ok:true,items:[{...request,status:"paid",receipt:{fake:true}}]}),undefined)});
 it("shows Send fields immediately and resolves exact identity inline without losing compose state",async()=>{const compose=await source("src/components/product/personal/PaymentComposeForm.tsx"),send=await source("src/components/product/personal/PaymentIntentWorkspace.tsx");assert.match(compose, /"Recipient"\s*:\s*"Request from"/);assert.match(compose, />Amount</);assert.match(compose,/Purpose \(optional\)/);assert.match(compose,/\/api\/recipients\/search/);assert.match(compose,/parseRecipientResolveResponse/);assert.match(compose,/We couldn't find that ZephiPay username/);assert.match(compose,/Solana Devnet wallet/);assert.doesNotMatch(send,/Choose who to pay|RecipientExperience/);assert.doesNotMatch(`${compose}\n${send}`,/\/api\/send/)});
 it("keeps Request in-place, idempotent, pending, and backed only by public request APIs",async()=>{const ui=await source("src/components/product/personal/PaymentRequestWorkspace.tsx"),activity=await source("src/components/product/personal/PaymentRequestActivity.tsx");assert.match(ui,/flow="request"/);assert.match(ui,/title="Review request"/);assert.match(ui,/>Send request</);assert.match(ui,/Idempotency-Key/);assert.match(ui,/title="Request sent"/);assert.match(ui,/No payment has been made and no receipt exists yet/);assert.match(activity,/\/api\/payment-requests\?limit=20/);assert.match(activity,/role==="payer"/);assert.match(activity,/Accepted — payment not completed/);assert.match(activity,/status==="paid"\?"Paid"/);assert.doesNotMatch(`${ui}\n${activity}`,/fake receipt|\/api\/send/)});
 it("keeps Transfer visible and intentionally non-operational",async()=>{const workspace=await source("src/components/marketing/personal-workspace/PersonalWorkspace.tsx");assert.match(workspace, /id: "transfer", label: "Transfer"/);assert.match(workspace,/Transfer is not available in this beta/);assert.doesNotMatch(workspace,/activeMode === "transfer"[\s\S]{0,300}fetch\(|activeMode === "transfer"[\s\S]{0,300}\/api\/send/)});
 it("keeps Request BFF authentication server-only, no-store, bounded, and same-origin",async()=>{const client=await source("src/lib/paymentRequests/serverClient.ts"),route=await source("src/app/api/payment-requests/route.ts"),accept=await source("src/app/api/payment-requests/[id]/accept/route.ts");assert.match(client,/import "server-only"/);assert.match(client,/getSession\(\)/);assert.match(client,/Authorization:`Bearer \$\{token\}`/);assert.match(client,/cache:"no-store"/);assert.match(client,/AbortSignal\.timeout\(5_000\)/);assert.match(route,/hasTrustedOrigin/);assert.match(route,/validIdempotencyKey/);assert.match(accept,/parseRequestCommand/);assert.doesNotMatch(`${client}\n${route}`,/localStorage|solana-devnet/)});
});async function source(path:string){return readFile(new URL(`../${path}`,import.meta.url),"utf8")}
