"use client";
import {useCallback,useEffect,useRef,useState} from "react";import {useRouter} from "next/navigation";import {Button} from "@/components/ui/Button";import {RecipientExperience} from "./RecipientExperience";import {parsePaymentIntentResponse,type PaymentIntent} from "@/lib/paymentIntents/contract";import {parseExecutionResponse,parseReceiptResponse,type PublicExecution,type PublicReceipt} from "@/lib/paymentIntents/executionContract";import {isCanonicalSolanaAddressInput,paymentIntentRequestFromRecipient} from "@/lib/paymentIntents/requests";
type FormState={walletFallback:string;amount:string;purpose:string};const emptyForm={walletFallback:"",amount:"",purpose:""};type ErrorBody={error?:string};
export function PaymentIntentWorkspace({recoveryId,inPlace=false}:{recoveryId?:string;inPlace?:boolean}){const router=useRouter(),[form,setForm]=useState<FormState>(emptyForm),[intent,setIntent]=useState<PaymentIntent>(),[execution,setExecution]=useState<PublicExecution>(),[receipt,setReceipt]=useState<PublicReceipt>(),[error,setError]=useState<string>(),[readError,setReadError]=useState(false),[busy,setBusy]=useState(Boolean(recoveryId)),[advancedOpen,setAdvancedOpen]=useState(false),[recipientResetKey,setRecipientResetKey]=useState(0);const creationKey=useRef<string|undefined>(undefined),polling=useRef(false);
 const readReceipt=useCallback(async(id:string,signal?:AbortSignal)=>{const response=await fetch(`/api/payment-intents/${encodeURIComponent(id)}/receipt`,{cache:"no-store",credentials:"same-origin",signal});const raw:unknown=await response.json().catch(()=>undefined),parsed=parseReceiptResponse(raw);if(!response.ok||!parsed)throw new Error(safe(raw,"Unable to load the durable receipt."));setReceipt(parsed);window.dispatchEvent(new Event("zephipay:activity-refresh"));},[]);
 const readExecution=useCallback(async(id:string,signal?:AbortSignal)=>{if(polling.current)return;polling.current=true;try{const response=await fetch(`/api/payment-intents/${encodeURIComponent(id)}/execution`,{cache:"no-store",credentials:"same-origin",signal});const raw:unknown=await response.json().catch(()=>undefined),parsed=parseExecutionResponse(raw);if(!response.ok||!parsed)throw new Error(safe(raw,"Unable to read payment status."));setExecution(parsed);setReadError(false);if(parsed.status==="settled")await readReceipt(id,signal);return parsed.status;}finally{polling.current=false}},[readReceipt]);
 useEffect(()=>{if(!recoveryId)return;const c=new AbortController();(async()=>{try{const response=await fetch(`/api/payment-intents/${encodeURIComponent(recoveryId)}`,{cache:"no-store",credentials:"same-origin",signal:c.signal});const raw:unknown=await response.json().catch(()=>undefined),parsed=parsePaymentIntentResponse(raw);if(!response.ok||!parsed)throw new Error(safe(raw,"Unable to load this payment intent."));setIntent(parsed.paymentIntent);if(parsed.paymentIntent.status==="processing")await readExecution(recoveryId,c.signal)}catch(e){if(!c.signal.aborted)setError(message(e))}finally{if(!c.signal.aborted)setBusy(false)}})();return()=>c.abort()},[recoveryId,readExecution]);
 useEffect(()=>{if(!intent||!execution||!["ready","processing","pending"].includes(execution.status))return;const c=new AbortController();let timer:ReturnType<typeof setTimeout>;const poll=async()=>{try{const status=await readExecution(intent.id,c.signal);if(status&&["ready","processing","pending"].includes(status))timer=setTimeout(poll,2500)}catch{if(!c.signal.aborted){setReadError(true);timer=setTimeout(poll,4000)}}};timer=setTimeout(poll,2500);return()=>{c.abort();clearTimeout(timer)}},[intent,execution?.status,readExecution]);
 function update(field:keyof FormState,value:string){setForm(v=>({...v,[field]:value}));creationKey.current=undefined;setError(undefined)}
 async function createIntent(e:React.FormEvent){e.preventDefault();if(busy)return;const body=paymentIntentRequestFromRecipient({...form,recipientInput:""}),validation=validateForm(form,body);if(validation){setError(validation);return}creationKey.current??=crypto.randomUUID();setBusy(true);try{const response=await fetch("/api/payment-intents",{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json","Idempotency-Key":creationKey.current},body:JSON.stringify(body)}),raw:unknown=await response.json().catch(()=>undefined),parsed=parsePaymentIntentResponse(raw);if(!response.ok||!parsed)throw new Error(safe(raw,"Unable to create the payment intent."));setIntent(parsed.paymentIntent);rememberIntent(parsed.paymentIntent.id)}catch(e){setError(message(e))}finally{setBusy(false)}}
 async function confirmAndExecute(){if(!intent||busy)return;setBusy(true);setError(undefined);try{let confirmed=intent;if(intent.status!=="processing"){const r=await fetch(`/api/payment-intents/${encodeURIComponent(intent.id)}/confirm`,{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json"},body:JSON.stringify({requestHash:intent.requestHash,expectedVersion:intent.version})}),raw:unknown=await r.json().catch(()=>undefined),parsed=parsePaymentIntentResponse(raw);if(!r.ok||!parsed)throw new Error(safe(raw,"Unable to confirm the payment."));confirmed=parsed.paymentIntent;setIntent(confirmed)}const response=await fetch(`/api/payment-intents/${encodeURIComponent(confirmed.id)}/execute`,{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json"},body:JSON.stringify({requestHash:confirmed.requestHash,expectedVersion:confirmed.version})}),raw:unknown=await response.json().catch(()=>undefined),parsed=parseExecutionResponse(raw);if(![200,202].includes(response.status)||!parsed)throw new Error(safe(raw,"Unable to start payment execution."));setExecution(parsed);if(parsed.status==="settled")await readReceipt(confirmed.id)}catch(e){setError(message(e))}finally{setBusy(false)}}
 function rememberIntent(id:string){if(inPlace)window.history.replaceState(null,"",`/personal?intent=${encodeURIComponent(id)}#personal-workspace`);else router.replace(`/personal/send?intent=${encodeURIComponent(id)}`)}
 function clearIntentLocation(){if(inPlace)window.history.replaceState(null,"","/personal#personal-workspace");else router.replace("/personal/send")}
 function backToCompose(){setIntent(undefined);setExecution(undefined);setReceipt(undefined);setError(undefined);clearIntentLocation()}
 function startAnother(){creationKey.current=undefined;setIntent(undefined);setExecution(undefined);setReceipt(undefined);setError(undefined);setForm(emptyForm);setAdvancedOpen(false);setRecipientResetKey(v=>v+1);clearIntentLocation()}
 const composeView=<Shell step="Compose" title="Choose who to pay" description="Find a Payment Identity by exact username. Advanced Wallet is available only as an alternate destination input for this Mock Rail beta.">{error&&!intent?<Notice message={error}/>:null}{busy&&recoveryId&&!intent?<p>Recovering the authoritative payment…</p>:<div className="grid gap-7"><RecipientExperience key={recipientResetKey} onDirectorySelected={()=>{setAdvancedOpen(false);setForm(v=>({...v,walletFallback:""}))}} onUseAdvancedWallet={()=>setAdvancedOpen(true)} onIntentCreated={i=>{setIntent(i);rememberIntent(i.id)}}/><div className="border-t border-border-subtle pt-6"><button type="button" onClick={()=>setAdvancedOpen(v=>!v)} className="min-h-11 rounded-full border border-border-default px-5 text-sm font-medium">Advanced options · Send by wallet address</button></div>{advancedOpen?<form onSubmit={createIntent} className="grid gap-6 rounded-[1.4rem] border border-border-default bg-background/40 p-5" noValidate><p className="text-sm text-foreground-secondary">Enter a destination wallet for the current simulated Mock Rail beta. No Solana transaction will be submitted.</p><Field label="Destination wallet address" value={form.walletFallback} onChange={v=>update("walletFallback",v)}/><Field label="USDC amount" value={form.amount} onChange={v=>update("amount",v)}/><Field label="Purpose (optional)" value={form.purpose} onChange={v=>update("purpose",v)} placeholder="What is this payment for?"/><Button type="submit" loading={busy}>Review payment</Button></form>:null}</div>}</Shell>;
 const receiptView=receipt?<Shell step="Receipt" title="Payment settled" description="This durable receipt is the authoritative record returned by ZephiPay."><Details rows={[["Amount",`${receipt.amount} ${receipt.asset}`],["Recipient",receipt.recipient.type==="payment_identity"?`${receipt.recipient.displayName} (@${receipt.recipient.username})`:receipt.recipient.displayName],...(receipt.memo?[["Purpose",receipt.memo] as [string,string]]:[]),["Settled",formatTime(receipt.settledAt)],["Receipt ID",receipt.receiptId],["Execution ID",receipt.executionId],["Rail",receipt.rail.label]]}/><Button className="mt-6" variant="outline" onClick={startAnother}>Start another payment</Button></Shell>:null;
 const status=execution?.status;const statusTitle=status==="ready"?"Payment queued":status==="processing"?"Processing payment":status==="pending"?"Payment status is still being confirmed":status==="failed"?"Payment could not be completed":status==="cancelled"?"Payment cancelled":undefined;
 const identityRows:[string,string][]=intent?.recipientType==="payment_identity"?[["Verification",verificationLabel(intent.recipientSnapshot.verificationState)],["Trust confirmation",intent.recipientSnapshot.trustOutcome==="acknowledged"?"Acknowledged":"Not required"]]:[];
 const intentView=intent&&!receipt?<Shell step={status?"Status":"Review"} title={statusTitle??"Review payment"} description={status?"Status is read from the authoritative Mock Rail execution record.":"Check the details below, then send your payment when you are ready."}>{error?<Notice message={error}/>:null}{readError?<Notice message="Payment status is temporarily unavailable. ZephiPay will continue checking; this does not mean the payment failed."/>:null}<Details rows={[["Recipient",intent.recipientType==="payment_identity"?`${intent.recipientSnapshot.displayName} (@${intent.recipientSnapshot.username})`:intent.recipient],...identityRows,["Amount",`${intent.amount} ${intent.asset}`],...(intent.purpose?[["Purpose",intent.purpose] as [string,string]]:[]),["Created",formatTime(intent.createdAt)],["Intent ID",intent.id]]}/><div className="mt-7 flex flex-wrap gap-3">{!status?<><Button variant="outline" onClick={backToCompose} disabled={busy}>Back</Button><Button onClick={confirmAndExecute} loading={busy}>Send payment</Button></>:null}{status&&["ready","processing","pending"].includes(status)?<Button variant="outline" onClick={()=>readExecution(intent.id)} loading={busy}>Refresh status</Button>:null}{status&&["failed","cancelled"].includes(status)?<Button variant="outline" onClick={startAnother}>Start another payment</Button>:null}</div></Shell>:null;
 return <div><div className={intent?"hidden":undefined}>{composeView}</div>{receiptView??intentView}</div>}
function Shell({step,title,description,children}:{step:string;title:string;description:string;children:React.ReactNode}){return <section className="rounded-[2rem] border border-border-default bg-surface-glass p-6 shadow-[var(--shadow-medium)] backdrop-blur-2xl sm:p-9"><p className="text-xs uppercase tracking-[.18em] text-brand-secondary">{step}</p><h1 className="mt-4 text-3xl font-semibold sm:text-4xl">{title}</h1><p className="mt-4 max-w-2xl leading-7 text-foreground-secondary">{description}</p><div className="mt-8">{children}</div></section>}
function Field({label,value,onChange,...props}:{label:string;value:string;onChange:(v:string)=>void}&Omit<React.InputHTMLAttributes<HTMLInputElement>,"value"|"onChange">){return <label className="grid gap-2 text-sm font-medium">{label}<input {...props} value={value} onChange={e=>onChange(e.target.value)} className="h-12 rounded-xl border border-border-default bg-background/70 px-4 font-normal"/></label>}
function Details({rows}:{rows:[string,string][]}){return <dl className="grid gap-px overflow-hidden rounded-[1.4rem] border border-border-default bg-border-subtle sm:grid-cols-2">{rows.map(([l,v])=><div key={l} className="min-w-0 bg-background/75 p-5"><dt className="text-xs uppercase tracking-[.14em] text-foreground-muted">{l}</dt><dd className="mt-2 break-words text-sm">{v}</dd></div>)}</dl>}
function Notice({message}:{message:string}){return <div role="alert" className="mb-6 rounded-xl border border-red-400/25 bg-red-400/10 p-4 text-sm">{message}</div>};function formatTime(v:string){return new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(v))};function message(v:unknown){return v instanceof Error?v.message:"Payment service is temporarily unavailable."};function safe(v:unknown,f:string){return typeof v==="object"&&v!==null&&typeof(v as ErrorBody).error==="string"?(v as ErrorBody).error!:f}function validateForm(f:FormState,r:ReturnType<typeof paymentIntentRequestFromRecipient>){if(!isCanonicalSolanaAddressInput(f.walletFallback))return"Enter a canonical wallet address to continue.";if(!/^(?:0|[1-9]\d*)(?:\.\d{1,6})?$/.test(f.amount)||f.amount==="0")return"Enter a positive USDC amount with no more than 6 decimal places.";if(new TextEncoder().encode(f.purpose.trim()).length>120)return"Purpose must not exceed 120 UTF-8 bytes.";if(!r)return"Review the payment details and try again."}
function verificationLabel(value:"verified"|"unverified"|"pending"){return value==="verified"?"Verified":value==="pending"?"Pending verification":"Unverified"}
