"use client";
import {useRef,useState} from "react";
import {Button} from "@/components/ui/Button";
import {parseRecipientResolveResponse,parseRecipientSearchResponse,type PublicRecipient} from "@/lib/recipients/contract";
import {trustModeFor} from "@/lib/recipients/recipientState";

export type PaymentComposeValue={recipient:PublicRecipient;amount:string;purpose:string|null;trustAcknowledged:boolean};
export function PaymentComposeForm({flow,onReview,advanced}:Readonly<{flow:"send"|"request";onReview:(value:PaymentComposeValue)=>void;advanced?:React.ReactNode}>){
 const [username,setUsername]=useState(""),[amount,setAmount]=useState(""),[purpose,setPurpose]=useState(""),[resolved,setResolved]=useState<PublicRecipient>(),[trustAcknowledged,setTrustAcknowledged]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState<string>();const sequence=useRef(0);
 function changeRecipient(value:string){setUsername(value);setResolved(undefined);setTrustAcknowledged(false);setError(undefined)}
 async function submit(event:React.FormEvent){event.preventDefault();if(busy)return;const identity=username.trim().replace(/^@/,"");if(!identity||identity.length>64){setError("Enter a valid exact ZephiPay username.");return}if(!/^(?:0|[1-9]\d*)(?:\.\d{1,6})?$/.test(amount)||amount==="0"){setError("Enter a positive USDC amount with no more than 6 decimal places.");return}const cleanPurpose=purpose.trim();if(new TextEncoder().encode(cleanPurpose).length>120){setError("Purpose must not exceed 120 UTF-8 bytes.");return}setBusy(true);setError(undefined);const current=++sequence.current;try{let recipient=resolved;if(!recipient||recipient.username.toLowerCase()!==identity.toLowerCase()){const search=await fetch("/api/recipients/search",{method:"POST",credentials:"same-origin",cache:"no-store",headers:{"Content-Type":"application/json"},body:JSON.stringify({username:identity})}),searchRaw:unknown=await search.json().catch(()=>undefined),found=parseRecipientSearchResponse(searchRaw);if(!search.ok||!found){throw new Error(search.status===429?"Too many recipient checks. Wait a moment and try again.":"Recipient lookup is temporarily unavailable.")}if(!found.recipients[0])throw new Error("We couldn't find that ZephiPay username.");const response=await fetch(`/api/recipients/${encodeURIComponent(found.recipients[0].accountId)}`,{credentials:"same-origin",cache:"no-store"}),raw:unknown=await response.json().catch(()=>undefined),parsed=parseRecipientResolveResponse(raw);if(!response.ok||!parsed||parsed.recipient.payabilityState!=="available")throw new Error("This Payment Identity is not available right now.");recipient=parsed.recipient;setResolved(recipient)}if(current!==sequence.current)return;const mode=trustModeFor(recipient.verificationState);if(mode==="blocked")throw new Error("This Payment Identity is restricted and cannot be selected.");if(mode==="confirmation_required"&&!trustAcknowledged){setError("Review the verification status and acknowledge it before continuing.");return}onReview({recipient,amount,purpose:cleanPurpose||null,trustAcknowledged})}catch(reason){if(current===sequence.current)setError(reason instanceof Error?reason.message:"Recipient lookup is temporarily unavailable.")}finally{if(current===sequence.current)setBusy(false)}}
 const trust=resolved?trustModeFor(resolved.verificationState):undefined;
 return <form onSubmit={submit} className="grid gap-6" noValidate><label className="grid gap-2 text-sm font-medium">{flow==="send"?"Recipient":"Request from"}<input value={username} onChange={e=>changeRecipient(e.target.value)} autoComplete="off" spellCheck={false} placeholder="@username" className="h-12 rounded-xl border border-border-default bg-background/70 px-4 font-normal"/><span className="text-xs font-normal text-foreground-muted">Enter an exact ZephiPay username.</span></label><label className="grid gap-2 text-sm font-medium">Amount<input value={amount} onChange={e=>{setAmount(e.target.value);setError(undefined)}} inputMode="decimal" placeholder="0.00" className="h-12 rounded-xl border border-border-default bg-background/70 px-4 font-normal"/><span className="text-xs font-normal text-foreground-muted">USDC</span></label><label className="grid gap-2 text-sm font-medium">Purpose (optional)<input value={purpose} onChange={e=>{setPurpose(e.target.value);setError(undefined)}} placeholder={flow==="send"?"What is this payment for?":"What is this request for?"} className="h-12 rounded-xl border border-border-default bg-background/70 px-4 font-normal"/></label>{resolved?<div className="rounded-xl border border-border-default bg-background/50 p-4"><p className="font-medium">{resolved.displayName} (@{resolved.username})</p><p className="mt-1 text-sm text-foreground-secondary">{verificationLabel(resolved.verificationState)}</p>{trust==="confirmation_required"?<label className="mt-3 flex gap-3 text-sm"><input type="checkbox" checked={trustAcknowledged} onChange={e=>{setTrustAcknowledged(e.target.checked);setError(undefined)}}/>I confirmed this is the Payment Identity I intend to {flow==="send"?"pay":"request from"}.</label>:null}</div>:null}{error?<p role="alert" className="rounded-xl border border-red-400/25 bg-red-400/10 p-4 text-sm">{error}</p>:null}<Button type="submit" loading={busy}>{flow==="send"?"Review payment":"Review request"}</Button>{advanced}</form>
}
export function verificationLabel(value:PublicRecipient["verificationState"]){return value==="verified"?"Verified":value==="pending"?"Pending verification":value==="restricted"?"Restricted":"Unverified"}
