import { isPaymentIntentId } from "./contract";

export type ExecutionStatus = "ready" | "processing" | "pending" | "settled" | "failed" | "cancelled";
export type PublicExecution = Readonly<{ executionId:string; paymentIntentId:string; status:ExecutionStatus; createdAt:string; submittedAt?:string; settledAt?:string; failedAt?:string; receiptAvailable:boolean; receiptId?:string; failure?:Readonly<{code:string;message:string}>; retryAllowed:boolean; stillProcessing:boolean; reconciliationPending:boolean; rail:Readonly<{id:"mock";label:"Mock Rail"}> }>;
export type PublicRecipient = Readonly<{type:"payment_identity";displayName:string;username:string;verificationState:string;trustOutcome:string}|{type:"direct_wallet";displayName:"Wallet recipient"}>;
export type PublicReceipt = Readonly<{receiptId:string;paymentIntentId:string;executionId:string;status:"settled";amountRaw:string;amount:string;asset:"USDC";sender:Readonly<{displayName:"You"}>;recipient:PublicRecipient;memo:string|null;rail:Readonly<{id:"mock";label:"Mock Rail"}>;settledAt:string;providerReference?:string;verification:Readonly<{receiptSchemaVersion:1;evidenceType:string;evidenceVersion:number;requestHash:string}>}>;
export type ActivityItem = Readonly<{paymentIntentId:string;executionId?:string;receiptId?:string;status:"awaiting_confirmation"|"ready"|"processing"|"pending"|"completed"|"failed"|"cancelled";recipient:PublicRecipient;amountRaw:string;amount:string;asset:"USDC";memo:string|null;createdAt:string;settledAt?:string;receiptAvailable:boolean}>;

const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i, INTEGER=/^(?:0|[1-9]\d*)$/, AMOUNT=/^(?:0|[1-9]\d*)(?:\.\d{1,6})?$/;
const statuses=["ready","processing","pending","settled","failed","cancelled"] as const;
function record(v:unknown):v is Record<string,unknown>{return typeof v==="object"&&v!==null&&!Array.isArray(v)}
function date(v:unknown):v is string{return typeof v==="string"&&Number.isFinite(Date.parse(v))}
function recipient(v:unknown):PublicRecipient|undefined{if(!record(v)||typeof v.displayName!=="string")return;if(v.type==="direct_wallet"&&v.displayName==="Wallet recipient")return{type:"direct_wallet",displayName:"Wallet recipient"};if(v.type==="payment_identity"&&typeof v.username==="string"&&typeof v.verificationState==="string"&&typeof v.trustOutcome==="string")return{type:"payment_identity",displayName:v.displayName,username:v.username,verificationState:v.verificationState,trustOutcome:v.trustOutcome};}
function rail(v:unknown):v is {id:"mock";label:"Mock Rail"}{return record(v)&&v.id==="mock"&&v.label==="Mock Rail"}
export function parseExecutionResponse(v:unknown):PublicExecution|undefined{if(!record(v)||v.ok!==true||!record(v.execution))return;const e=v.execution;if(typeof e.executionId!=="string"||!UUID.test(e.executionId)||typeof e.paymentIntentId!=="string"||!isPaymentIntentId(e.paymentIntentId)||!statuses.includes(e.status as ExecutionStatus)||!rail(e.rail)||!date(e.createdAt)||typeof e.receiptAvailable!=="boolean"||typeof e.retryAllowed!=="boolean"||typeof e.stillProcessing!=="boolean"||typeof e.reconciliationPending!=="boolean")return;return e as unknown as PublicExecution;}
export function parseReceiptResponse(v:unknown):PublicReceipt|undefined{if(!record(v)||v.ok!==true||!record(v.receipt))return;const r=v.receipt,p=recipient(r.recipient);if(typeof r.receiptId!=="string"||typeof r.paymentIntentId!=="string"||!isPaymentIntentId(r.paymentIntentId)||typeof r.executionId!=="string"||!UUID.test(r.executionId)||r.status!=="settled"||typeof r.amountRaw!=="string"||!INTEGER.test(r.amountRaw)||typeof r.amount!=="string"||!AMOUNT.test(r.amount)||r.asset!=="USDC"||!p||(r.memo!==null&&typeof r.memo!=="string")||!rail(r.rail)||!date(r.settledAt)||!record(r.verification))return;return r as unknown as PublicReceipt;}
export function parseActivityResponse(v:unknown):readonly ActivityItem[]|undefined{if(!record(v)||v.ok!==true||!Array.isArray(v.items)||v.items.length>50)return;const out:ActivityItem[]=[];for(const i of v.items){if(!record(i)||typeof i.paymentIntentId!=="string"||!isPaymentIntentId(i.paymentIntentId)||!recipient(i.recipient)||typeof i.amountRaw!=="string"||!INTEGER.test(i.amountRaw)||typeof i.amount!=="string"||!AMOUNT.test(i.amount)||i.asset!=="USDC"||(i.memo!==null&&typeof i.memo!=="string")||!date(i.createdAt)||typeof i.receiptAvailable!=="boolean"||!["awaiting_confirmation","ready","processing","pending","completed","failed","cancelled"].includes(String(i.status)))return;out.push(i as unknown as ActivityItem)}return out;}
