import "server-only";
import { randomUUID } from "node:crypto";
import { authConfigured,getAuth0,paymentScopes } from "@/lib/auth0";
import { parsePaymentRequestCreateResponse,parsePaymentRequestListResponse,parsePaymentRequest } from "./contract";
export type RequestApiResult={status:number;body:unknown};
export async function callPaymentRequestApi(input:{method:"GET"|"POST";path:string;body?:unknown;idempotencyKey?:string;requestId?:string|null;response:"create"|"list"|"read"|"command"}) : Promise<RequestApiResult>{
  if(!authConfigured())return fail(503,"Payment request service is not configured.");const auth0=getAuth0();if(!await auth0.getSession())return fail(401,"Sign in is required.");const backend=process.env.ZEPHIPAY_BACKEND_URL?.trim(),audience=process.env.AUTH0_AUDIENCE?.trim();if(!backend||!audience)return fail(503,"Payment request service is not configured.");
  try{const {token}=await auth0.getAccessToken({audience,scope:paymentScopes});const response=await fetch(new URL(input.path,backend),{method:input.method,headers:{Accept:"application/json",Authorization:`Bearer ${token}`,"X-Request-Id":input.requestId&&/^[\x21-\x7e]{1,128}$/.test(input.requestId)?input.requestId:randomUUID(),...(input.body===undefined?{}:{"Content-Type":"application/json"}),...(input.idempotencyKey?{"Idempotency-Key":input.idempotencyKey}:{})},body:input.body===undefined?undefined:JSON.stringify(input.body),cache:"no-store",signal:AbortSignal.timeout(5_000)});const raw:unknown=await response.json().catch(()=>undefined);if(!response.ok)return fail([400,401,403,404,409].includes(response.status)?response.status:503,"Payment request could not be completed.");let parsed:unknown;if(input.response==="create")parsed=parsePaymentRequestCreateResponse(raw);else if(input.response==="list")parsed=parsePaymentRequestListResponse(raw);else if(input.response==="read")parsed=record(raw)&&raw.ok===true&&parsePaymentRequest(raw.paymentRequest)?raw:undefined;else parsed=record(raw)&&raw.ok===true&&parsePaymentRequest(raw.paymentRequest)?raw:undefined;return parsed?{status:response.status,body:parsed}:fail(502,"Payment request service returned an invalid response.");}catch{return fail(503,"Payment request service is temporarily unavailable.")}
}
function fail(status:number,error:string){return{status,body:{ok:false,error}}}function record(v:unknown):v is Record<string,unknown>{return typeof v==="object"&&v!==null&&!Array.isArray(v)}
