import type { Metadata } from "next";
import Script from "next/script";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/ThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Script
          id="zephyon-theme-init"
          strategy="beforeInteractive"
        >
          {`
            (() => {
              try {
                const stored =
                  localStorage.getItem("zephyon-theme") || "system";

                const hour = new Date().getHours();

                const period =
                  hour >= 6 && hour < 10
                    ? "morning"
                    : hour >= 10 && hour < 17
                      ? "day"
                      : hour >= 17 && hour < 21
                        ? "evening"
                        : "night";

                const systemDark =
                  window.matchMedia(
                    "(prefers-color-scheme: dark)"
                  ).matches;

                const theme =
                  stored === "adaptive"
                    ? period === "morning" || period === "day"
                      ? "light"
                      : "dark"
                    : stored === "system"
                      ? systemDark
                        ? "dark"
                        : "light"
                      : stored;

                document.documentElement.dataset.theme = theme;
                document.documentElement.dataset.themePreference = stored;
                document.documentElement.dataset.period = period;
                document.documentElement.style.colorScheme = theme;
              } catch {}
            })();
          `}
        </Script>

        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
